use_default_settings: true

general:
  debug: false
  instance_name: "SearXNG"

server:
  secret_key: "CHANGE_ME_LOCAL_SECRET"
  limiter: false
  image_proxy: true

ui:
  default_theme: simple
  default_locale: en

search:
  formats:
    - html
    - json

doi_resolvers:
  oadoi.org: "https://oadoi.org/"
  doi.org: "https://doi.org/"

default_doi_resolver: oadoi.org

outputs:
  - name: html
    template: simple.html
  - name: json
    template: json.html
